[package]
name = "binjs_generate_library"
version = "0.2.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[dependencies]
binjs_meta = { path = "../binjs_meta/", version = "*" }
itertools = "^0.8"

[dev-dependencies]
env_logger = "0.7.1"
log = "^0.4"
clap = "^2.0"
yaml-rust = "^0.4"
